// Turkish Language Constants for Anticca

export const TR = {
  // Brand
  siteName: 'Anticca',
  tagline: 'Antikanın Dijital Adresi',
  heroTitle: "İstanbul'un Saklı Kalmış Antikalarını Keşfedin",
  heroSubtitle: 'Türkiye\'nin en seçkin antikacılarından nadide parçalar, tek bir adreste.',

  // Navigation
  nav: {
    home: 'Ana Sayfa',
    products: 'Tüm Ürünler',
    shops: 'Dükkanlar',
    auction: 'Müzayede',
    cart: 'Sepetim',
    orders: 'Siparişlerim',
    account: 'Hesabım',
    adminPanel: 'Admin Paneli',
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
  },

  // Auth
  auth: {
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    email: 'E-posta',
    password: 'Şifre',
    confirmPassword: 'Şifre Tekrar',
    name: 'Ad Soyad',
    phone: 'Telefon',
    address: 'Adres',
    forgotPassword: 'Şifremi Unuttum',
    noAccount: 'Hesabınız yok mu?',
    hasAccount: 'Zaten hesabınız var mı?',
    loginError: 'Giriş yapılamadı. Lütfen bilgilerinizi kontrol edin.',
    registerError: 'Kayıt oluşturulamadı. Lütfen tekrar deneyin.',
    passwordMismatch: 'Şifreler eşleşmiyor.',
    weakPassword: 'Şifre en az 6 karakter olmalıdır.',
    invalidEmail: 'Geçerli bir e-posta adresi girin.',
    emailInUse: 'Bu e-posta adresi zaten kullanılıyor.',
  },

  // Products
  products: {
    title: 'Tüm Ürünler',
    featured: 'Öne Çıkan Ürünler',
    addToCart: 'Sepete Ekle',
    viewDetails: 'Detayları Gör',
    viewShopProducts: 'Dükkanın Tüm Ürünlerini Gör',
    outOfStock: 'Stokta Yok',
    inStock: 'Stokta',
    price: 'Fiyat',
    category: 'Kategori',
    era: 'Dönem',
    shop: 'Dükkan',
    noProducts: 'Ürün bulunamadı.',
    loadMore: 'Daha Fazla Göster',
  },

  // Shops
  shops: {
    title: 'Dükkanlar',
    featured: 'Öne Çıkan Dükkanlar',
    viewProducts: 'Dükkanın Ürünlerini Gör',
    address: 'Adres',
    phone: 'Telefon',
    city: 'Şehir',
    district: 'İlçe',
    noShops: 'Dükkan bulunamadı.',
    allProducts: 'Bu dükkanın tüm ürünleri',
  },

  // Filters
  filters: {
    title: 'Filtreler',
    apply: 'Filtreleri Uygula',
    clear: 'Filtreleri Temizle',
    priceRange: 'Fiyat Aralığı',
    minPrice: 'Min. Fiyat',
    maxPrice: 'Max. Fiyat',
    category: 'Kategori',
    era: 'Dönem',
    shop: 'Dükkan',
    city: 'Şehir',
    district: 'İlçe',
    search: 'Ara...',
    sortBy: 'Sırala',
    sortNewest: 'En Yeni',
    sortPriceAsc: 'Fiyat (Artan)',
    sortPriceDesc: 'Fiyat (Azalan)',
    allCategories: 'Tüm Kategoriler',
    allEras: 'Tüm Dönemler',
    allShops: 'Tüm Dükkanlar',
    allCities: 'Tüm Şehirler',
  },

  // Cart
  cart: {
    title: 'Sepetim',
    empty: 'Sepetiniz boş.',
    continueShopping: 'Alışverişe Devam Et',
    checkout: 'Ödemeye Geç',
    total: 'Toplam',
    subtotal: 'Ara Toplam',
    quantity: 'Adet',
    remove: 'Kaldır',
    unitPrice: 'Birim Fiyat',
    itemTotal: 'Tutar',
  },

  // Orders
  orders: {
    title: 'Siparişlerim',
    empty: 'Henüz siparişiniz yok.',
    orderNumber: 'Sipariş No',
    date: 'Tarih',
    status: 'Durum',
    total: 'Toplam',
    details: 'Sipariş Detayı',
    items: 'Ürünler',
    shippingAddress: 'Teslimat Adresi',
    paymentPending: 'Ödeme Bekleniyor',
    paid: 'Ödendi',
    preparing: 'Hazırlanıyor',
    shipped: 'Kargolandı',
    delivered: 'Teslim Edildi',
    cancelled: 'İptal Edildi',
  },

  // Admin
  admin: {
    title: 'Admin Paneli',
    dashboard: 'Kontrol Paneli',
    shops: 'Dükkan Yönetimi',
    products: 'Ürün Yönetimi',
    auctions: 'Müzayede Yönetimi',
    orders: 'Sipariş Yönetimi',
    users: 'Kullanıcılar',
    addShop: 'Yeni Dükkan Ekle',
    editShop: 'Dükkanı Düzenle',
    addProduct: 'Yeni Ürün Ekle',
    startAuction: 'Müzayede Başlat',
    editProduct: 'Ürünü Düzenle',
    updateStatus: 'Durumu Güncelle',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    activate: 'Aktif Et',
    deactivate: 'Pasif Et',
    active: 'Aktif',
    inactive: 'Pasif',
    confirmDelete: 'Bu işlemi geri alamazsınız. Silmek istediğinize emin misiniz?',
    shopName: 'Dükkan Adı',
    shopDescription: 'Dükkan Açıklaması',
    productName: 'Ürün Adı',
    productDescription: 'Ürün Açıklaması',
    selectShop: 'Dükkan Seçin',
    uploadImages: 'Görsel Yükle',
    uploadLogo: 'Logo Yükle',
    upload3dModel: '3D Model Yükle (.glb)',
    product3dUrl: '3D Model URL',
    saleType: 'Satış Tipi',
    fixedPrice: 'Sabit Fiyat',
    auction: 'Müzayede (Açık Artırma)',
    auctionStart: 'Başlangıç Zamanı',
    auctionEnd: 'Bitiş Zamanı',
    startingBid: 'Başlangıç Fiyatı',
    minIncrement: 'Min. Artış',
    stock: 'Stok',
    totalOrders: 'Toplam Sipariş',
    totalProducts: 'Toplam Ürün',
    totalShops: 'Toplam Dükkan',
    recentOrders: 'Son Siparişler',
    noAccess: 'Bu sayfaya erişim yetkiniz yok.',
  },

  auction: {
    upcoming: 'Müzayede Yakında',
    live: 'Canlı Müzayede',
    ended: 'Müzayede Sona Erdi',
    startsIn: 'Başlamasına:',
    endsIn: 'Bitimine:',
    startingBid: 'Açılış Fiyatı',
    currentBid: 'Mevcut En Yüksek Teklif',
    placeBid: 'Teklif Ver',
    bidHistory: 'Teklif Geçmişi',
    minBidWarning: 'Minimum teklif: ',
    loginToBid: 'Teklif vermek için giriş yapmalısınız',
    successBid: 'Teklifiniz başarıyla alındı',
    outbid: 'Biri daha yüksek teklif verdi!',
    soldTo: 'Kazanan:',
    participant: 'Katılımcı',
    noBidsYet: 'Henüz teklif yok, ilk teklifi siz verin.',
    winner: 'Müzayedeyi Kazandınız! 🎉',
  },

  // Common
  common: {
    loading: 'Yükleniyor...',
    error: 'Bir hata oluştu.',
    success: 'İşlem başarılı.',
    required: 'Bu alan zorunludur.',
    currency: '₺',
    tryAgain: 'Tekrar Dene',
    back: 'Geri',
    next: 'İleri',
    submit: 'Gönder',
    close: 'Kapat',
    yes: 'Evet',
    no: 'Hayır',
  },

  // Footer
  footer: {
    rights: 'Tüm hakları saklıdır.',
    about: 'Hakkımızda',
    contact: 'İletişim',
    terms: 'Kullanım Şartları',
    privacy: 'Gizlilik Politikası',
    description: 'İstanbul\'un en seçkin antikacılarını tek çatı altında buluşturan dijital pazar yeri.',
  },

  // Errors
  errors: {
    notFound: 'Sayfa bulunamadı.',
    unauthorized: 'Bu sayfaya erişim yetkiniz yok.',
    generic: 'Bir hata oluştu. Lütfen tekrar deneyin.',
    networkError: 'Bağlantı hatası. İnternet bağlantınızı kontrol edin.',
  },

  // Payment
  payment: {
    redirecting: 'Ödeme sayfasına yönlendiriliyorsunuz...',
    processing: 'Ödeme işleniyor...',
    success: 'Ödeme başarılı!',
    failed: 'Ödeme başarısız. Lütfen tekrar deneyin.',
    shopier: 'Shopier ile Öde',
  },
};

export default TR;
